services: 
  frontend:
    build:
      context: ./Frontend       
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    container_name: frontend_app
  
  backend: 
    build:
      context: ./Backend         
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    container_name: backend_app